-- Load core modules
require("nvim.core.options")
require("nvim.core.keymaps")
require("nvim.core.autocmds")
require("nvim.core.filetype-settings")
require("nvim.core.performance")
require("nvim.core.terminal")
require("nvim.core.checkpoint")
require("nvim.core.visual").setup()
require("nvim.core.docs").setup()
require("nvim.core.colorscheme").setup()
