// Generated by matugen. Loaded as QML component: Colors { id: colors }
// Palette: material (muted, less poppy – surfaces and outlines)
import QtQuick

QtObject {
    // --- BASE SURFACES ---
    property color background: "#1b1016"
    property color surface: "#1b1016"
    property color surfaceContainer: "#291c22"
    property color surfaceBright: "#44353c"

    // --- ACCENTS ---
    property color primary: "#ffaed9"
    property color secondary: "#f0b8c7"
    property color tertiary: "#ffb2b8"
    property color error: "#ffb4ab"

    // --- CONTAINERS ---
    property color primaryContainer: "#890064"
    property color secondaryContainer: "#633b48"
    property color tertiaryContainer: "#6e353c"
    property color errorContainer: "#93000a"

    // --- TEXT ON ACCENTS ---
    property color textOnPrimary: "#610046"
    property color textOnSecondary: "#4a2531"
    property color textOnTertiary: "#532026"
    property color textOnError: "#690005"
    property color textOnPrimaryContainer: "#ffd8ea"
    property color textOnSecondaryContainer: "#ffd9e2"
    property color textOnTertiaryContainer: "#ffdadb"
    property color textOnErrorContainer: "#ffdad6"

    // --- GENERAL TEXT ---
    property color textMain: "#f3dde5"
    property color textDim: "#d6c1c9"
    property color textMuted: "#9f8c94"

    // --- BORDERS & SHADOWS ---
    property color border: "#9f8c94"
    property color borderSubtle: "#52434a"
    property color panelShadow: Qt.rgba(0, 0, 0, 0.35)

    // --- URGENT (always bright red + black "!", independent of theme) ---
    property color urgent: "#e53935"
    property color textOnUrgent: "#000000"

    // --- REUSABLE ACCENTS ---
    property color accent1: primary
    property color textOnAccent1: textOnPrimary
    property color accent2: secondary
    property color textOnAccent2: textOnSecondary
    property color accent3: tertiary
    property color textOnAccent3: textOnTertiary
    property color accent4: error
    property color textOnAccent4: textOnError
    property color accent5: primaryContainer
    property color textOnAccent5: textOnPrimaryContainer
    property color accent6: secondaryContainer
    property color textOnAccent6: textOnSecondaryContainer

    // --- WORKSPACE SLOTS: muted (surface/outline/containers) ---
    property var workspaceColors: [surfaceContainer, border, surfaceBright, secondaryContainer, tertiaryContainer, borderSubtle, surface, primaryContainer]
    property var workspaceSlotColors: workspaceColors
    property var workspaceSlotOnColors: [textMain, textMuted, textMain, textOnSecondaryContainer, textOnTertiaryContainer, textDim, textMain, textOnPrimaryContainer]

    // --- WIDGET PILLS: muted (outlines, surface variants, soft containers) ---
    property var widgetPillColors: [
        "#9f8c94",
        "#52434a",
        "#291c22",
        "#44353c",
        "#633b48",
        "#6e353c",
        "#1b1016",
        "#890064"
    ]
    property var widgetTextOnPillColors: [
        "#f3dde5",
        "#d6c1c9",
        "#f3dde5",
        "#f3dde5",
        "#ffd9e2",
        "#ffdadb",
        "#f3dde5",
        "#ffd8ea"
    ]

    // --- BAR SIZING ---
    property int radius: 6
    property int spacing: 8
    property int fontSize: 12
    property int iconSize: 20

    // --- TYPOGRAPHY SCALE (use these instead of literal pixelSize) ---
    property int fontXs: fontSize - 3
    property int fontSm: fontSize - 1
    property int fontMd: fontSize
    property int fontLg: fontSize + 2
    property int fontXl: fontSize + 4
    property string fontMain: "JetBrainsMono Nerd Font"
    property int trayIconSize: iconSize
    property int clockFontSize: fontSize
    property int cpuFontSize: fontSize
    property int widgetPillRadius: radius
    property int widgetPillPaddingH: spacing
    property int widgetPillPaddingV: 4
    property string widgetIconFont: fontMain

    // High-contrast text colors (auto-generated)
    property color textPrimary: "#ffffff"
    property color textSecondary: "#e0e0e0"
    property color textHighContrast: "#ffffff"
}
