// Generated by matugen. Loaded as QML component: Colors { id: colors }
// Palette: material (muted, less poppy – surfaces and outlines)
import QtQuick

QtObject {
    // --- BASE SURFACES ---
    property color background: "#1c1016"
    property color surface: "#1c1016"
    property color surfaceContainer: "#291c22"
    property color surfaceBright: "#44353c"

    // --- ACCENTS ---
    property color primary: "#ffafd7"
    property color secondary: "#f0b7c6"
    property color tertiary: "#ffb2b6"
    property color error: "#ffb4ab"

    // --- CONTAINERS ---
    property color primaryContainer: "#8a0061"
    property color secondaryContainer: "#643b47"
    property color tertiaryContainer: "#6e353a"
    property color errorContainer: "#93000a"

    // --- TEXT ON ACCENTS ---
    property color textOnPrimary: "#620044"
    property color textOnSecondary: "#4a2530"
    property color textOnTertiary: "#532025"
    property color textOnError: "#690005"
    property color textOnPrimaryContainer: "#ffd8e9"
    property color textOnSecondaryContainer: "#ffd9e1"
    property color textOnTertiaryContainer: "#ffdadb"
    property color textOnErrorContainer: "#ffdad6"

    // --- GENERAL TEXT ---
    property color textMain: "#f4dde5"
    property color textDim: "#d7c1c9"
    property color textMuted: "#9f8c93"

    // --- BORDERS ---
    property color border: "#9f8c93"
    property color borderSubtle: "#524349"

    // --- URGENT (always bright red + black "!", independent of theme) ---
    property color urgent: "#e53935"
    property color textOnUrgent: "#000000"

    // --- REUSABLE ACCENTS ---
    property color accent1: primary
    property color textOnAccent1: textOnPrimary
    property color accent2: secondary
    property color textOnAccent2: textOnSecondary
    property color accent3: tertiary
    property color textOnAccent3: textOnTertiary
    property color accent4: error
    property color textOnAccent4: textOnError
    property color accent5: primaryContainer
    property color textOnAccent5: textOnPrimaryContainer
    property color accent6: secondaryContainer
    property color textOnAccent6: textOnSecondaryContainer

    // --- WORKSPACE SLOTS: muted (surface/outline/containers) ---
    property var workspaceColors: [surfaceContainer, border, surfaceBright, secondaryContainer, tertiaryContainer, borderSubtle, surface, primaryContainer]
    property var workspaceSlotColors: workspaceColors
    property var workspaceSlotOnColors: [textMain, textMuted, textMain, textOnSecondaryContainer, textOnTertiaryContainer, textDim, textMain, textOnPrimaryContainer]

    // --- WIDGET PILLS: muted (outlines, surface variants, soft containers) ---
    property var widgetPillColors: [
        "#9f8c93",
        "#524349",
        "#291c22",
        "#44353c",
        "#643b47",
        "#6e353a",
        "#1c1016",
        "#8a0061"
    ]
    property var widgetTextOnPillColors: [
        "#f4dde5",
        "#d7c1c9",
        "#f4dde5",
        "#f4dde5",
        "#ffd9e1",
        "#ffdadb",
        "#f4dde5",
        "#ffd8e9"
    ]

    // --- BAR SIZING ---
    property int radius: 6
    property int spacing: 8
    property int fontSize: 12
    property int iconSize: 20
    property string fontMain: "JetBrainsMono Nerd Font"
    property int trayIconSize: iconSize
    property int clockFontSize: fontSize
    property int cpuFontSize: fontSize
    property int widgetPillRadius: radius
    property int widgetPillPaddingH: spacing
    property int widgetPillPaddingV: 4
    property string widgetIconFont: fontMain

    // High-contrast text colors (auto-generated)
    property color textPrimary: "#ffffff"
    property color textSecondary: "#e0e0e0"
    property color textHighContrast: "#ffffff"
}
