// Generated by matugen. Loaded as QML component: Colors { id: colors }
// Palette: rainbow (maximum color variety)
import QtQuick

QtObject {
    // --- BASE SURFACES ---
    property color background: "#1e100c"
    property color surface: "#1e100c"
    property color surfaceContainer: "#2b1c18"
    property color surfaceBright: "#473530"

    // --- ACCENTS ---
    property color primary: "#ffb5a1"
    property color secondary: "#f2bb99"
    property color tertiary: "#f5bc7c"
    property color error: "#ffb4ab"

    // --- CONTAINERS ---
    property color primaryContainer: "#882000"
    property color secondaryContainer: "#643e24"
    property color tertiaryContainer: "#653e08"
    property color errorContainer: "#93000a"

    // --- TEXT ON ACCENTS ---
    property color textOnPrimary: "#601400"
    property color textOnSecondary: "#4a2810"
    property color textOnTertiary: "#482a00"
    property color textOnError: "#690005"
    property color textOnPrimaryContainer: "#ffdbd1"
    property color textOnSecondaryContainer: "#ffdbc7"
    property color textOnTertiaryContainer: "#ffddba"
    property color textOnErrorContainer: "#ffdad6"

    // --- GENERAL TEXT ---
    property color textMain: "#f9dcd5"
    property color textDim: "#dcc1ba"
    property color textMuted: "#a48b85"

    // --- BORDERS ---
    property color border: "#a48b85"
    property color borderSubtle: "#55423d"

    // --- URGENT (always bright red + black "!", independent of theme) ---
    property color urgent: "#e53935"
    property color textOnUrgent: "#000000"

    // --- REUSABLE ACCENTS ---
    property color accent1: primary
    property color textOnAccent1: textOnPrimary
    property color accent2: secondary
    property color textOnAccent2: textOnSecondary
    property color accent3: tertiary
    property color textOnAccent3: textOnTertiary
    property color accent4: error
    property color textOnAccent4: textOnError
    property color accent5: primaryContainer
    property color textOnAccent5: textOnPrimaryContainer
    property color accent6: secondaryContainer
    property color textOnAccent6: textOnSecondaryContainer

    // --- WORKSPACE SLOTS: full accent + container variety ---
    property var workspaceColors: [primary, secondary, tertiary, error, primaryContainer, secondaryContainer, tertiaryContainer, errorContainer]
    property var workspaceSlotColors: workspaceColors
    property var workspaceSlotOnColors: [textOnPrimary, textOnSecondary, textOnTertiary, textOnError, textOnPrimaryContainer, textOnSecondaryContainer, textOnTertiaryContainer, textOnErrorContainer]

    // --- WIDGET PILLS: varied order so adjacent widgets get different hues (rainbow) ---
    property var widgetPillColors: [
        "#ffb5a1",
        "#f5bc7c",
        "#ffb4ab",
        "#f2bb99",
        "#882000",
        "#653e08",
        "#93000a",
        "#643e24"
    ]
    property var widgetTextOnPillColors: [
        "#601400",
        "#482a00",
        "#690005",
        "#4a2810",
        "#ffdbd1",
        "#ffddba",
        "#ffdad6",
        "#ffdbc7"
    ]

    // --- BAR SIZING ---
    property int radius: 6
    property int spacing: 8
    property int fontSize: 12
    property int iconSize: 20
    property string fontMain: "JetBrainsMono Nerd Font"
    property int trayIconSize: iconSize
    property int clockFontSize: fontSize
    property int cpuFontSize: fontSize
    property int widgetPillRadius: radius
    property int widgetPillPaddingH: spacing
    property int widgetPillPaddingV: 4
    property string widgetIconFont: fontMain

    // High-contrast text colors (auto-generated)
    property color textPrimary: "#ffffff"
    property color textSecondary: "#e0e0e0"
    property color textHighContrast: "#ffffff"
}
